num=input('Enter a four numbers: ')
num_tuple=tuple(str(num))
num_product = eval('*'.join(num))
num_list = list(num_tuple)
num_list.reverse()
num_reverse = int(''.join(num_list))
num_sort = int(''.join(sorted(str(num))))
print(num_tuple)
print(num_product)
print(num_list)
print(num_reverse)
print(num_sort)